name: Build With devkitARM-r45

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up devkitARM-r45
        run: |
          curl -L https://github.com/devkitPro/pacman/releases/download/v1.0.2/devkitpro-pacman.amd64.deb
          sudo apt-get install gdebi-core
          sudo gdebi devkitpro-pacman.amd64.deb
          cp -d dka/devkitARM-r45 /opt/devkitpro/dka-r45
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=/opt/devkitpro/dka-r45

      # Runs a set of commands using the runners shell
      - name: Set up aemstro
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
