name: Build With devkitARM-r45

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up devkitARM-r45
        run: |
          echo T3st

      # Runs a set of commands using the runners shell
      - name: Set up aemstro
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
