name: Build With devkitARM-r45

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up devkitARM-r45
        run: |
          
          sudo chmod +x setup.sh
          ./setup.sh

      # Runs a set of commands using the runners shell
      - name: Set up aemstro
        run: |
          git clone https://github.com/smealum/aemstro.git
          cp - d aemstro /opt/devkitpro/aemstro
          export AEMSTRO=/opt/devkitpro/aemstro
