name: Build With devkitARM-r45

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up devkitARM-r45
        run: |
          
          sudo chmod +x setup.sh
          ./setup.sh
          mkdir -p ~/artifacts
          cp BCSTM-Player.3dsx ~/artifacts
          cp BCSTM-Player.cia ~/artifacts

      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v2
        with:
          path: ~/artifacts/*
          name: build
          
