name: Standart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_tag: ${{ steps.build.outputs.commit_tag }}
      commit_hash: ${{ steps.build.outputs.commit_hash }}
      author_name: ${{ steps.build.outputs.author_name }}
      committer_name: ${{ steps.build.outputs.committer_name }}
      commit_subject: ${{ steps.build.outputs.commit_subject }}
      commit_message: ${{ steps.build.outputs.commit_message }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Set Up devkitARM-r45
        run: |
          
          sudo chmod +x setup.sh
          ./setup.sh
          cd /home/runner/
         
          git clone https://github.com/Tobi-D7/lpp-3ds-next.git
          export D7=/home/runner/lpp-3ds-next
          cd $D7/
          
          sudo mkdir /opt/devkitpro
          
          cp -r 'dka/devkitARM-r45/' '/opt/devkitpro/dka-r45'
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=/opt/devkitpro/dka-r45
          git clone https://github.com/smealum/aemstro.git aemstro
          sudo cp -r 'aemstro/' '/opt/devkitpro/aemstro'
          export AEMSTRO=/opt/devkitpro/aemstro

          cd $DEVKITARM/arm-none-eabi/lib && make CRT=3dsx
          
          cd $D7/
          make
          mkdir -p ~/artifacts
          cp lpp-3ds-next.3dsx ~/artifacts
          cp lpp-3ds-next.elf ~/artifacts
          cp lpp-3ds-next.smdh ~/artifacts
          make clean
          make -j $DCITRA3DSCOMPATIBLE
          cp lpp-3ds-next.3dsx ~/artifacts/lpp-3ds-next-citra.3dsx
          cp lpp-3ds-next.elf ~/artifacts/lpp-3ds-next-citra.elf
          cp lpp-3ds-next.smdh ~/artifacts/lpp-3ds-next-citra.smdh


      - name: pb
        uses: actions/upload-artifact@v2
        with:
          path: ~/artifacts/*
          name: build


  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      # ...
      - name: "Build & test"
        run: |
          
          sudo chmod +x setup.sh
          ./setup.sh
          cd /home/runner/
         
          git clone https://github.com/Tobi-D7/lpp-3ds-next.git
          export D7=/home/runner/lpp-3ds-next
          cd $D7/
          
          sudo mkdir /opt/devkitpro
          
          cp -r 'dka/devkitARM-r45/' '/opt/devkitpro/dka-r45'
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=/opt/devkitpro/dka-r45
          git clone https://github.com/smealum/aemstro.git aemstro
          sudo cp -r 'aemstro/' '/opt/devkitpro/aemstro'
          export AEMSTRO=/opt/devkitpro/aemstro
          cd $DEVKITARM/arm-none-eabi/lib && make CRT=3dsx
          
          cd $D7/
          make
          mkdir -p ~/artifacts
          cp lpp-3ds-next.3dsx ~/artifacts
          cp lpp-3ds-next.elf ~/artifacts
          cp lpp-3ds-next.smdh ~/artifacts
          make clean
          make -j $DCITRA3DSCOMPATIBLE
          cp lpp-3ds-next.3dsx ~/artifacts/lpp-3ds-next-citra.3dsx
          cp lpp-3ds-next.elf ~/artifacts/lpp-3ds-next-citra.elf
          cp lpp-3ds-next.smdh ~/artifacts/lpp-3ds-next-citra.smdh
          

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: v
          prerelease: true
          title: "lpp-3ds-next"
          files: |
            /devbb/*.3dsx
            /devbb/*.elf
            /devbb/*.smdh
            *.3dsx
            *.elf
            *.smdh
