name: Build With devkitARM-r45

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up devkitARM-r45
        run: |
          
          sudo chmod +x setup.sh
          ./setup.sh
          cd $D7/
          make
          mkdir -p ~/artifacts
          cp lpp-3ds-updated.3dsx ~/artifacts
          cp lpp-3ds-updated.elf ~/artifacts
          cp lpp-3ds-updated.smdh ~/artifacts

      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v2
        with:
          path: ~/artifacts/*
          name: build
          
