name: Standard

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_tag: ${{ steps.git_info.outputs.commit_tag }}
      commit_hash: ${{ steps.git_info.outputs.commit_hash }}
      author_name: ${{ steps.git_info.outputs.author_name }}
      committer_name: ${{ steps.git_info.outputs.committer_name }}
      commit_subject: ${{ steps.git_info.outputs.commit_subject }}
      commit_message: ${{ steps.git_info.outputs.commit_message }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Set Up devkitARM-r45
        run: |
          sudo chmod +x setup.sh
          ./setup.sh
          cd /home/runner/
         
          git clone https://github.com/Tobi-D7/lpp-3ds-next.git
          export D7=/home/runner/lpp-3ds-next
          cd $D7/
          
          sudo mkdir -p /opt/devkitpro
          
          cp -r 'dka/devkitARM-r45/' '/opt/devkitpro/dka-r45'
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=/opt/devkitpro/dka-r45
          git clone https://github.com/smealum/aemstro.git aemstro
          sudo cp -r 'aemstro/' '/opt/devkitpro/aemstro'
          export AEMSTRO=/opt/devkitpro/aemstro
          cd $DEVKITARM/arm-none-eabi/lib && make CRT=3dsx
          
          cd $D7/
          make
          mkdir -p ~/artifacts
          cp lpp-3ds-next.3dsx ~/artifacts
          cp lpp-3ds-next.elf ~/artifacts
          cp lpp-3ds-next.smdh ~/artifacts
          make clean
          make -j $DCITRA3DSCOMPATIBLE
          cp lpp-3ds-next.3dsx ~/artifacts/lpp-3ds-next-citra.3dsx
          cp lpp-3ds-next.elf ~/artifacts/lpp-3ds-next-citra.elf
          cp lpp-3ds-next.smdh ~/artifacts/lpp-3ds-next-citra.smdh

      - name: Extract Git Info
        id: git_info
        run: |
          echo "commit_tag=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT
          echo "commit_hash=$(git log --format=%h -1)" >> $GITHUB_OUTPUT
          echo "author_name=$(git log -1 $GITHUB_SHA --pretty=%aN)" >> $GITHUB_OUTPUT
          echo "committer_name=$(git log -1 $GITHUB_SHA --pretty=%cN)" >> $GITHUB_OUTPUT
          echo "commit_subject=$(git log -1 $GITHUB_SHA --pretty=%s)" >> $GITHUB_OUTPUT
          echo "commit_message=$(git log -1 $GITHUB_SHA --pretty=%b)" >> $GITHUB_OUTPUT

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ~/artifacts/*
          name: build
          retention-days: 5

  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest
    needs: build
    env:
      COMMIT_TAG: ${{ needs.build.outputs.commit_tag }}
      COMMIT_HASH: ${{ needs.build.outputs.commit_hash }}
      AUTHOR_NAME: ${{ needs.build.outputs.author_name }}
      COMMIT_SUBJECT: ${{ needs.build.outputs.commit_subject }}
      COMMIT_MESSAGE: ${{ needs.build.outputs.commit_message }}
    outputs:
      current_date: ${{ steps.date_info.outputs.current_date }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Date
        id: date_info
        run: |
          CURRENT_DATE=$(date +"%Y%m%d-%H%M%S")
          echo "current_date=$CURRENT_DATE" >> $GITHUB_OUTPUT
          echo "Generated date: $CURRENT_DATE"
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
